Algoritmo "semnome"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 25/02/2019
Var
n1 : real


Inicio
escreval ("Digite um numero")
leia(n1)

se (n1 = 5) entao
   escreval("o numero digitado é o numero  5")
senao
escreval("o numero digitado não é o numero  5")
fimse



Fimalgoritmo